{% set name = "cmlib" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmlib-{{ version }}.zip
  sha256: 71e8c419b3507f2b7f26d26c12559ade9a7e3739eaa05d2fa42d5ec40600ac20

build:
  number: 0
  noarch: python
  entry_points:
    - cmlib_demo = cmlib.demo:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy >=1.11
    - python >=3.5

test:
  imports:
    - cmlib
  commands:
    - pip check
  requires:
    - pip
    - pyqt >=5.12

about:
  home: https://github.com/titusjan/cmlib
  summary: Color Map Library with harmonized data from different catalogs. Includes PyQt selection widgets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - titusjan
